export const SET_TIME_SPAN_FROM = 'SET_TIME_SPAN_FROM';
export const SET_TIME_SPAN_TO = 'SET_TIME_SPAN_TO';
export const SET_MENU_OPEN = 'SET_MENU_OPEN';
export const SET_DATA_CATEGORY = 'SET_DATA_CATEGORY';
